### PR TITLE
Added installation instructions for FreeNAS.

### PR DESCRIPTION
**Pull request by thebaron06**
The installation of Runalyze inside a FreeNAS jail might be a little bit
tricky. Therefore I wrote a short installation instruction. This also
contains a code snippet that deals with perl errors that are printed
when the local is not set correctely. On my box this fixed the fit file
import.

### CODE REVIEW

**Comment by mipapo** [comment]
Hi, i wouldn't add this to the repo here. We are going to have an additional administration documentation. I would rewrite this in markdown and mention your name their. Would it be okay?

**Comment by thebaron06** [comment]
Sure, if this is the place for your documentation then it would be best to place it there.

**Comment by thebaron06** [comment]
Ok, rewrote in markdown done.
In which repo do you want to place it @mipapo ?

**Comment by mipapo** [comment]
oh :D i rewrote it just in markdown too...I just changed some parts and headings. 
The repo is just in work and not structure is not ready. 
Just add it to the root folder of Runalyze/admin-docs

**Comment by thebaron06** [comment]
See https://github.com/Runalyze/admin-docs/pull/1

**Pull request closed without merging**
