### PR TITLE
Feature/refactor fit parser

### PR DESCRIPTION
**Pull request by undertrained**
Import FIT files without calling Perl. Simplifies files by a lot.

A few fields might have to be added again (e.g. estimated VDOT), but that should be done by someone who uses these.

### CODE REVIEW

**Comment by laufhannes** [comment]
Can you rebase (or merge with upstream) such that Travis can run the unit tests and check how good the new parser works?

Every kind of 'special' field (like vo2max estimate) and especially developer fields are covered by the unit tests. Looking at the commit history of that library, I don't really get if developer fields are supported or if only their definitions are read, see adriangibbons/php-fit-file-analysis@4bc43b8f2e2f8498af72c12f3fd0536d34455dcc (but there were three more commits since then):
> _Support for Definitions only; Data is just skipped over (+= $field_defn['size']) - will need to add functionality to process Developer Data_

**Comment by laufhannes** [comment]
Ah, @mipapo just merged it, but he already checked locally that unit tests for fit files do not even start, as `new \adriangibbons\phpFITFileAnalysis()` requires an absolute path.

**Comment by laufhannes** [comment]
@mipapo Merging composer.json is not enough, composer.lock has to be updated as well ;)

**Comment by mipapo** [comment]
@laufhannes Damn - no time for that. I think @undertrained should just fix it an let run the unittests https://docs.runalyze.com/en/latest/contribute.html#run-the-tests

**Comment by undertrained** [comment]
I ran `composer update` locally which updated all that's mentioned in composer.json. I can commit that version of composer.lock, but it's a bigger diff (not restricted to php-fit-analysis)...

**Comment by mipapo** [comment]
fuuu**

**Comment by mipapo** [comment]
Just have to look how I can revert that merge

**Comment by mipapo** [comment]
@undertrained  Sorry for the merge - Could you please make a new pull request?
You should not run `composer update`. run `composer install` - This one uses the versions mentioned in composer.lock
Run `composer require <repo> <version>` to update the composer.lock file

**Comment by undertrained** [comment]
Hmm, let's see... I wanted to push a commit in my own branch for composer.lock, but now git complains about remote changes that I didn't pull.. But I don't want these changes, and I can't simply redo the pull request...

*diff, patch, CVS, good times...*

**Comment by mipapo** [comment]
(diff patch CSV -> bad old time)

git reset --hard <hash of your own latest commit should do it>

**Pull request merged**
