### PR TITLE
New icons for sports

### PR DESCRIPTION
**Pull request by grzeg1**
Good people from icons8.com gave Runalyze license for OpenSource projects.
I'll share account data in private mail.

### CODE REVIEW

**Comment by laufhannes** [comment]
Nice icons. How easy will it be to add new icons later on? I'd really like to have a larger selection.

(And, but that's only an individual styling, in calendar view they look a bit too large for me.)

**Comment by grzeg1** [comment]
Adding new icons is as simple as:
- adding font+css if necessary
- adding icon identifiers to SportFactory::getIconOptions
So now you can add e.g. 'fa fa-search' and the magnifying glass will appear (font is already included).

I made them a bit bigger because IMO they look nicer this way than when they were small. More details - you instantly know what the icon shows. But it does not matter, you can remove db update for styling and they will stay small.

**Comment by laufhannes** [comment]
Okay. I think it's a small overload to add more and more font files, but probably there exists a solution to combine them later on.

**Comment by sportsaddict** [comment]
The new icons are really nice but honestly I'm a bit sad about my special Teakwon-Do Icon has now gone for good (You kindly added it in the former Trac System with #1609 after combining icons into sports.gif).
There seems to be (yet) no martial arts icon whatsoever within icon8's collection.
And yes, I know that this issue might only affect me or a very small group of users, thus having minor priority on that. But just in case some day any icon like that appears at icon8, I'd really appreciate adding it again :)

**Comment by laufhannes** [comment]
That's why I asked how easy it is to add new icons. Although it's not the prettiest way to mix different icon sets, it's good to give users a choice.

**Pull request merged**
