### PR TITLE
fixes for laps

### PR DESCRIPTION
**Pull request by grzeg1**

### CODE REVIEW

**Comment by laufhannes** [comment]
Your fixes contain short array notation which is PHP 5.4 but we're still supporting 5.3.

Note: I think fixes for lap window go into 2.1 while the first fix goes into 2.0.x as well. I'll add it there afterwards.

**Comment by mipapo** [comment]
We should not support 5.3. There are no more updates for 5.3.
5.4 will be EOS soon...

**Comment by grzeg1** [comment]
`Runalyze is a modern application and therefore we want to use the most modern web techniques. We will not try to support any outdated browser versions. `
Can we do the same for PHP? ;)

**Comment by grzeg1** [comment]
Changed syntax to 5.3 until 5.4+ confirmed

**Comment by laufhannes** [comment]
I guess now I'll have to manually merge relevant parts of it to 2.0.x-branch?

And: do you use some tool that automatically corrects stylings to your preferences or is it done by hand? Especially when applying these changes by hand to our online version it's hard to get relevant parts out of a diff. 
If we want to use a fixed styleguide we should discuss it and apply these changes all at once to keep diffs readable.

**Comment by grzeg1** [comment]
I'm using PHPStorm, it seems to autocorrect stylings to match the `.editorconfig` you defined in whole file. I try to apply Code Reformat only to selected lines (to whole file only when changes are more than 50%)  I don't know, maybe we should autocorrect all the files with some tool just as you did with newlines?

**Comment by grzeg1** [comment]
Re: FIT files: It's partly regarding #1270. I thought if there is an option to disable pauses, the user would get whole workout time for TRIMP. `applyPauses()` seems to remove points which are within pauses. If I'm wrong here I can remove the modifications for FIT files.

**Comment by grzeg1** [comment]
Re: manual backporting - there's this `cherry-pick` option for git (never used it yet). Probably there's also support for it in IDEs.
I try to keep every change in a separate commit to make it easier.

**Comment by grzeg1** [comment]
Also make sure you merge 2.0.x changes to trunk as soon as possible.

**Comment by laufhannes** [comment]
Removing all pauses is something else then disabling autodetection of pauses.

I'm not sure if the unset-case every occurs. For the file I checked there are no points recorded between stop and start. And that's what probably all devices do: They stop recording if a user presses stop. 
The whole method is only necessary as pauses are saved at the end of a fit-file. Without applying them there's just a large gap.

And as I sad: If a user wants to have values in between he must not press stop.

**Pull request merged**
