### PR TITLE
monthly stats plugin

### PR DESCRIPTION
**Pull request by grzeg1**

### CODE REVIEW

**Comment by laufhannes** [comment]
Can the plugin be loaded? It is still missing in `inc/plugin/pluginmap.php`.

**Comment by grzeg1** [comment]
I told you we should drop all the generated files from source ;)
I have one other plugin for tests in my tree so I'm not generating the pluginmap as it'll break things.
Also it seems the plugin install does not work (missing cli.pluginmap.php script)

**Comment by grzeg1** [comment]
to be clear ;) - it's fully working in my install

**Comment by laufhannes** [comment]
Yeah, you told so and I'm trying to move all old classes so that they can be localized based on their namespace. Still, that's not completely done so far.

And you're right, generating the pluginmap is only possible via `php build/build.php pluginmap`, not through admin view.

But how can it work? Did you change something in the plugin factory or in the Autoloader? If I remove any plugin from my pluginmap, it can't be loaded anymore.

**Comment by laufhannes** [comment]
Okay, I removed the pluginmap with dc725096daa8f24be2b9e4a188dae8928cc7a4f0.

**Pull request merged**
