### PR TITLE
add swissTopo to leaflet

### LINKED ISSUE #1818: Swiss topo map
Hi, could you add the map.geo.admin.ch tiles to the map selection?
Thanks.

possible references:
https://www.procrastinatio.org/examples/more-leaflet.html
https://www.procrastinatio.org/examples/more-leaflet.js

### PR DESCRIPTION
**Pull request by Salzi**
This PR should fix #1818

### CODE REVIEW

**Comment by Salzi** [comment]
Where would be the right place to document that a registration is needed? [See here](https://www.geo.admin.ch/de/geo-dienstleistungen/geodienste/darstellungsdienste-webmapping-webgis-anwendungen/programmierschnittstelle-api/anmeldung.html)

**Comment by mipapo** [comment]
https://github.com/Runalyze/admin-docs/blob/master/configuration.rst 
But it will not be added to v4.1 anymore

**Comment by Salzi** [comment]
Thanks. Created an PR in the admin-docs
Feel free to add it whenever you think it's ready. I'm not familiar with travis and don't know whats wrong with it. Do I have to change something?

**Comment by laufhannes** [comment]
You can ignore Travis as it currently fails for all pull requests of 'external' contributors.

**Comment by Salzi** [comment]
Found a bug: The layer is not visible in the public link view (shared). This is also the case for other Layers which are not visible by default like MapboxOutdoor. It seems that Runalyze.Options is not valid in the shared view. Don't know how to solve this :-/

**Comment by Salzi** [comment]
Fixed it the same way as @laufhannes fixed #2162

**Pull request closed without merging**
