### PR TITLE
[WIP] add initial vagrant configuration

### PR DESCRIPTION
**Pull request by maglnet**
This should make it easier for developers to setup a working Runalyze installation.

If you have vagrant installed, `vagrant up` should setup a virtual machine, which has runalyze installed and is available at http://localhost:8080

Todo:
- [x] perform `composer install` if no `vendor/` directory exists
- [x] perform runalyze installation
- [x] perform npm install
- [x] perform gulp install
- [x] copy `config.yml` if it doesn't exist
- [x] make database accessible from the host
- [x] add documentation to README
- [x] add documentation to Runalyze/admin-docs - Runalyze/admin-docs#23
- [ ] add installation for timezone detection 

feel free to give your feedback :)

### CODE REVIEW

**Review by laufhannes — COMMENTED** [review]
I personally don't know anything about Vagrant, so I can't provide profound feedback and I won't be able to provide support for this part of the repo later on, but I guess that's not a problem at all.

Concerning the file locations: Are the files in `data/vagrant/` meant to be edited by users? The `data/` directory is meant for all installation-specific files that won't be touched by updates, so that directory should be empty. I guess `app/vagrant/` fits better, but I don't know if there's any _best practice_.

@mipapo does probably know more about this topic than I do.

**Comment by maglnet** [comment]
Just a short explanation about vagrant:
Vagrant is (not only) meant to help developers setting up a development environment. It should help with those "but it works on my machine" issues, since the environment is the same for all developers.

The files within `data/vagrant` are only needed once to install the virtual machine and configure apache and MySQL, so they do not really belong to the application so
imho the `app` directory is not the right place for those files. I don't know if there's a *best practice* for file location, I'll check some other repositories.

Am 3. Oktober 2016 21:43:51 MESZ, schrieb Hannes <notifications@github.com>:

**Comment by maglnet** [comment]
btw: i have no idea how to fix the tryvis build error, seems this has something to do with automatic deployment:
```
The command "openssl aes-256-cbc -K $encrypted_d056b0ac7927_key -iv $encrypted_d056b0ac7927_iv -in bin/deploy_rsa.enc -out /tmp/deploy_rsa -d" failed and exited with 1 during .
```

**Comment by laufhannes** [comment]
I think we can ignore travis for this pr, as there are no changes in any php file. Travis fails because of https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions. I guess we need to wrap the first four lines of `before_install` in some `'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ...; fi'`.

**Pull request closed without merging**
