### PR TITLE
Add initial webapp manifest

### PR DESCRIPTION
**Pull request by maglnet**
According to the [WebAppManifest](https://www.w3.org/TR/appmanifest/), here is a simple web app manifest for Runalyze.

After installing Runalyze on the home screen of a mobile device, it will have some additional features:
* short splash screen in `#222222` with "Runalyze" during loading
* no URL-Bar any more (makes scrolling more comfortable, since the page always has the full height of the screen)

### CODE REVIEW

**Comment by mipapo** [comment]
Favicon path is wrong assets/v2.x/img/favicon.ico

**Comment by maglnet** [comment]
According to a chat with @mipapo the favicon should exist in the folder `web/assets/v2.x/img` but it doesn't. /cc @laufhannes 
So please just give me feedback, which favicon I should reference, I'll fix my commits then.

**Comment by laufhannes** [comment]
The favicon has been moved from `web/assets/v2.x/img` to the web root folder `web/` (as that's the officially recommended place for favicons) in a22a449fb3c1c5583214b035482d2c02331faf9f.

Sadly, there are currently some more places where the html head is included:
 - [x] `app/Resources/views/base.html.twig`
 - [ ] `app/Resources/views/system/base.html.twig`
 - [x] `inc/tpl/tpl.Frontend.header.php`
 - [ ] `inc/tpl/tpl.FrontendShared.header.php`
 - [ ] `inc/tpl/tpl.FrontendSharedIframe.header.php`
 - [ ] `inc/tpl/tpl.adminHeader.php`

I think the two files that have been touched so far are the important ones (especially for the purpose of providing additional features when opening Runalyze from the home screen), but can you still add the manifest to the other ones as well?

**Comment by maglnet** [comment]
The link to the manifest has been added to the other files as well.

**Pull request merged**
