### PR TITLE
Fix dates in form plot.

### PR DESCRIPTION
**Pull request by grzeg1**
Calculate date from index the same way as we calculated index from date, not via day of year.

### CODE REVIEW

**Comment by laufhannes** [comment]
It seems to me that the indices for 'All years' are not centered around 12pm (the other selections seem fine). In my case, I get all selections working with
```php
$index = strtotime($StartDay.' 12:00 +'.($d-$AddDays).'days').'000';
```

Calling `strtotime` in the loop should avoid any dst-problems. Can you verify that? I don't trust myself in this topic anymore ...

And - probably not directly connected to the time shift bug: For 2015 there's no data for the 31.12. for me ... I think we have to use `UNIX_TIMESTAMP("'.$StartDay.'" + INTERVAL '.($NumberOfDays+1).' DAY) - 1` or just `'.$EndTime.'` in the query?

**Comment by mipapo** [comment]
#1783

**Comment by grzeg1** [comment]
WIll play with it.
Sounds strange as we set
`$StartDay = LocalTime::fromServerTime($StartTime)->format('Y-m-d');`
and then
`$StartTime = strtotime($StartDay) + 1800 * 24;`
(this should be written as `3600*12`)
so it should be always at noon.
Maybe some kind of a math problem with large numbers precision?

**Comment by laufhannes** [comment]
It's at noon on that specific date, yes. But assuming that every day has 24 hours is wrong if dst comes into play. (Although I'm not sure if it's only a one-hour-shift that I see there and it seems to not depend on whether the date is in winter or summer.)

And the number is in the range of a normal timestamp, that shouldn't be that large. Adding `'000'` happens later and from then on it's handled as a string.

**Comment by grzeg1** [comment]
I don't thing it can be DST related.
DST will only come into play when there are datetimes and offsets. We operate on unix timestamps for calculations&plots - there's no DST in these. And activities' times are reduced to full days, so they will not be affected by DST either. Hour later or earlier, we'll still get the same day.

**Comment by laufhannes** [comment]
The whole plot has a continuous x axis, it's not limited to days. The tooltip shows the data nearest to the mouse position. If all data points are indexed with a timestamp representing midnight, the tooltip will show '29.04.2016' as matching data point from '28.04.2016 12:00' to '29.04.2016 12:00'. That's why all indices should be at noon, such that the tooltip shows the daily values exactly from '29.04.2016 00:00' to '29.04.2016 23:59'.

What you are describing is true for the query and the calculations: There we reduce everything to days and operate on unix timestamps, right. And there is no problem.

But for plots we use the user's time zone (which is used in all time-related functions like `strtotime()`, as we set the user's time zone as server time zone). That's required as the plotting library `flot` is in js and js uses the browser's time zone, i.e. the computer's time zone (and we assume that it's equal to the account's time zone).

---

Of course, it's nearly impossible to see if multiple years are shown, and even if the time range is short, a sensitive mouse / hand is required to move the pointer pixel by pixel. But I can't reproduce a large shift anymore.

Still, using `$StartTime = mktime(0, 0, 0, 3, 1, 2016);` and `echo date('d.m.Y H:i', substr($index, 0, -3)).'<br>';` I get:
```
26.03.2016 12:00
27.03.2016 13:00
```
and that's the index that's used in the plot and that may cause a minimal shift between the date in the tooltip and the real date of the data.

**Comment by grzeg1** [comment]
+Show actual time range instead of just "Choose time range"

**Comment by grzeg1** [comment]
Sorry, everything seems perfect, and for 'All years' the data is so squashed for me that I can only see every other day, so I guess it can only be used as a 'general view', not for examining detailed values.

**Pull request merged**
